type Query {
  "Fetch a list of tracks for the homepage grid"
  tracksForHome: [Track!]!
  "Fetch a specific track by ID"
  track(id: ID!): Track!
  "Fetch a specific module by ID"
  module(id: ID!): Module!
}

"Educational modules teaching a specific topic"
type Track {
  "The unique identifier for the track"
  id: ID!
  "The title of the track"
  title: String!
  "The track's primary author"
  author: Author!
  "The URL of the track's illustration, used in the track card and track detail page"
  thumbnail: String
  "The track's approximate length to complete, in minutes"
  length: Int
  "The number of modules contained in this track"
  modulesCount: Int
  "The track's full description, which may include Markdown"
  description: String
  "The number of times this track has been viewed"
  numberOfViews: Int
  "The ordered list of modules that make up this track"
  modules: [Module!]!
}

"An author of a track or module"
type Author {
  "The unique identifier for the author"
  id: ID!
  "The author's first and last name"
  name: String!
  "The URL of the author's profile picture"
  photo: String
}

"A single unit of teaching. Multiple modules compose a track"
type Module {
  "The unique identifier for the module"
  id: ID!
  "The title of the module"
  title: String!
  "The module's length, in minutes"
  length: Int
  "The module's text content, which may include Markdown; for video modules, this is the enriched transcript"
  content: String
  "The URL of the module's video, when the module is video-based"
  videoUrl: String
}

type Mutation {
  "Increment the number of views for a track when its card is clicked"
  incrementTrackViews(id: ID!): IncrementTrackViewsResponse!
}

"Response payload returned after attempting to increment a track's view count"
type IncrementTrackViewsResponse {
  "Similar to an HTTP status code, represents the status of the mutation"
  code: Int!
  "Whether the mutation completed successfully"
  success: Boolean!
  "A human-readable message for display in the UI"
  message: String!
  "The updated track after a successful mutation; null if the mutation failed"
  track: Track
}
